Repository robocup-logistics/rcll-rulebook, pull requests merged in 2024-04, with the labels that each got.

#100 switch to f39
  .circleci/config.yml
  Makefile
  rulebook.tex
Labels: enhancement

#101 update description of challenge field to refbox changes
  rulebook.tex
Labels: rule-change, vote-in-progress

#102 update challenge field graphic
  figures/challenge-field2021.pdf
  figures/challenge-field2021.tex
  rulebook.tex
Labels: simple-fix, vote-in-progress
